
---
- name: Playbook for creating users on servers
  hosts: centos
  become: yes
  vars:
    users:
      - mkl
      - zdv
      - qwe

  tasks:
  
  - name: Test connection
    ping:

  - name: Добавить пользователей из списка с добавлением его в группу 'wheel'. Группа 'wheel' даёт права sudo
    user:
      name: "{{ item }}"
      password: $6$jxlP17sUuVBiYwmR$z60upKu6.BNt.41y4BZN0f/d29VuF5Olna9nJd346QliGZb7eRkXSBZekpqdvyF6UDT7rFA2nurMYMlQFjusg. 
      shell: /bin/bash
      groups: wheel
      append: yes
    loop: "{{ users }}"

  - name: Создать 2048-битовый SSH ключ для пользователей в ~<username>/.ssh/<username>-ssh-key
    user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/{{ item }}-ssh-key
    loop: "{{ users }}"

  - name: Установить authorized key из файлов <username>-ssh-key.pub
    shell: cat /home/{{ item }}/.ssh/{{ item }}-ssh-key.pub >> /home/{{ item }}/.ssh/authorized_keys
    loop: "{{ users }}"
